spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=*
spring.mvc.cors.allowed-headers=*

spring.devtools.restart.enabled=true

security.jwt.secret=wTPebcUEEpd-JWyEShszqeOjM_xY52jh0zsNcp1E_wqjiIxyj9gLx-u0Vfyt1LSVr3Nq78pj86hSHX7qKa-hyQ
security.jwt.issuer=keliocity
security.jwt.exp-minutes=60